CREATE DATABASE IF NOT EXISTS tutorias;
USE tutorias;

CREATE TABLE contador_publico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    estatura VARCHAR(10),
    carrera VARCHAR(100),
    peso VARCHAR(10),
    fecha_nacimiento DATE,
    sexo VARCHAR(20),
    edad INT,
    estado_civil VARCHAR(50),
    trabaja VARCHAR(10),
    lugar_nacimiento VARCHAR(100),
    domicilio_actual VARCHAR(150),
    telefono VARCHAR(20),
    cp VARCHAR(10),
    email VARCHAR(100),
    tipo_vivienda TEXT,
    tipo_vivienda_propiedad TEXT,
    tipo_otro VARCHAR(100),
    num_personas INT,
    parentesco VARCHAR(100),
    nombre_padre VARCHAR(100),
    edad_padre INT,
    trabaja_padre VARCHAR(10),
    profesion_padre VARCHAR(100),
    tipo_trabajo_padre VARCHAR(100),
    domicilio_padre VARCHAR(150),
    telefono_padre VARCHAR(20),
    nombre_madre VARCHAR(100),
    profesion_madre VARCHAR(100),
    tipo_trabajo_madre VARCHAR(100),
    domicilio_madre VARCHAR(150),
    telefono_madre VARCHAR(20)
);
