
CREATE TABLE datos_familiares (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vivienda VARCHAR(50),
    tipo VARCHAR(50),
    tipo_otro VARCHAR(100),
    num_personas INT,
    parentesco VARCHAR(100),
    nombre_padre VARCHAR(100),
    edad_padre INT,
    trabaja_padre VARCHAR(10),
    profesion_padre VARCHAR(100),
    tipo_trabajo_padre VARCHAR(100),
    domicilio_padre VARCHAR(255),
    telefono_padre VARCHAR(20),
    nombre_madre VARCHAR(100),
    profesion_madre VARCHAR(100),
    tipo_trabajo_madre VARCHAR(100),
    domicilio_madre VARCHAR(255),
    telefono_madre VARCHAR(20),
    ingresos_familia VARCHAR(100),
    ingresos_propios VARCHAR(100),
    relacion_familia TEXT,
    dificultades_familia TEXT,
    tipo_dificultades TEXT,
    actitud_familia TEXT,
    relacion_padre TEXT,
    actitud_padre TEXT,
    relacion_madre TEXT,
    actitud_madre TEXT,
    ligado_afectivamente VARCHAR(50),
    porque_ligado TEXT,
    quien_educacion TEXT,
    quien_influye_carrera TEXT,
    otros_datos_familiares TEXT,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
